package com.model.arithmetic3.dao.mapper;

import com.model.arithmetic3.dao.domain.FileLog;
import com.model.arithmetic3.dao.domain.FileLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    long countByExample(FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    int deleteByExample(FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    int insert(FileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    int insertSelective(FileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    List<FileLog> selectByExample(FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    FileLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") FileLog record, @Param("example") FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    int updateByExample(@Param("record") FileLog record, @Param("example") FileLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    int updateByPrimaryKeySelective(FileLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_log
     *
     * @mbg.generated Tue May 19 14:42:16 CST 2020
     */
    int updateByPrimaryKey(FileLog record);
}